version: '3.9'
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - EXPOSE_PORT=5000
  client:
    build: ./client
    ports:
      - 3000:3000
    environment:
      - EXPOSE_PORT=3000
