version: '3.9'
secrets:
  psql-user:
    file: ./secrets/psql-user.txt
  psql-pass:
    file: ./secrets/psql-pass.txt

services:
  server:
    build:
      context: ./nest
      dockerfile: ./Dockerfile
    ports:
      - ${APP_SERVER_PORT}:5005
    environment:
      - EXPOSE_PORT=5005
      - PSQL_USER=${PSQL_USER}
      - PSQL_PASS=${PSQL_PASS}

  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - ${APP_CLIENT_PORT}:3000
    environment:
      - EXPOSE_PORT=3000
      - APP_SERVER_PORT=${APP_SERVER_PORT}

  pg-server:
    image: postgres
    ports:
      - ${APP_PSQL_SERVER_PORT}:5432
    secrets:
      - psql-user
      - psql-pass
    environment:
      - PSQL_USER_FILE=/run/secrets/psql-user
      - PSQL_PASSWORD_FILE=/run/secrets/psql-pass
      - PSQL_DB_NAME=${PSQL_DB_NAME}
    volumes:
      - ./pg-data/:/var/lib/postgresql/data
    container_name: pg-server

  pg-client:
    build:
      context: ./pg-client
      dockerfile: ./Dockerfile
    ports:
      - ${APP_PSQL_CLIENT_PORT}:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}