version: '3.9'
services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "5001:5000"
    environment:
      - EXPOSE_PORT=5000
    volumes:
      - ./server/src:/app/src
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      - EXPOSE_PORT=3000
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
